### PR TITLE
#4: QueryResultRow does not instantiate the row data

### LINKED ISSUE #4: `QueryResultRow` does not instantiate the row data
## Describe the bug
`QueryResultRow` does not instantiate the row data, instead it just references the mutable JDBC `ResultSet`. That can be moved away from the expected row or closed completely.

## To Reproduce
Returned data from `DBTable.insert` cannot be retrieved.

## Expected behavior
Instantiate the row data, so working with the iterator is safer (also can safely use `toList`)

### LINKED ISSUE #27: Add option(s) to get result column without column name
## Background
Sometimes it it useful to get result (from `QueryResultRow`) column without column name. For example, when function returns single result, and it is not named:
```sql
CREATE OR REPLACE FUNCTION public.convert_old_schema_to_new_schema(
    IN  i_old_schema JSONB
) RETURNS JSONB AS
$$
```
Currently I believe one has to use raw Java `resultSet` of `QueryResultRow` to get column with index 1, balta doesn't support that directly.

## Feature
Option (or options) to get `QueryResultRow` column value without column name, for example by index, or if is has only one column - without anything.

### PR DESCRIPTION
**Pull request by benedeki**
* `QueryResultRow` is now instantiated, so can be used even after connection close
* columns can be referred by their index not just name (1 based); for that reason `QueryResultRow` now has `columnCount` property too
*  `QueryResultRow` now has `rowNumber` property too
* `JsonBString` deprecated, replaced by `SimpleJsonString`
* setup for separation of unit and integration tests
* integration tests database setup
* github build action enhanced to support integration tests

Closes #4
Closes #27

### CODE REVIEW

File: balta/src/main/scala/za/co/absa/db/balta/classes/QueryResultRow.scala [hunk 1]
```diff
@@ -16,83 +16,154 @@
...
+  type TransformerFnc[T] = Object => T
+  type Extractor = ResultSet => Option[Object]
+  type Extractors = Vector[Extractor]
+
+  def apply(resultSet: ResultSet)(implicit fieldNames: FieldNames, extractors: Extractors): QueryResultRow = {
+    val fields = extractors.map(_(resultSet))
+    new QueryResultRow(resultSet.getRow, fields, fieldNames)
+  }
+
+  def fieldNamesFromMetdata(metaData: ResultSetMetaData): FieldNames = {
```
Comment (lsulak) [inline balta/src/main/scala/za/co/absa/db/balta/classes/QueryResultRow.scala:137]:
```suggestion
  def fieldNamesFromMetadata(metaData: ResultSetMetaData): FieldNames = {
```

File: balta/src/main/scala/za/co/absa/db/balta/classes/QueryResult.scala [hunk 2]
```diff
@@ -16,32 +16,44 @@
...
-      val result = resultSet.next()
-      resultSetHasNext = Some(result)
-      result
+    if (nextRow.isEmpty) {
+      try {
+        if (resultSet.next()) {
+          nextRow = Some(QueryResultRow(resultSet))
+        }
+      } catch {
+        case _: SQLException =>  // TODO Do nothing
```
Comment (lsulak) [inline balta/src/main/scala/za/co/absa/db/balta/classes/QueryResult.scala:44]: what are the possible causes of this? TODO indicates that you might want to discuss this further?

File: balta/src/main/scala/za/co/absa/db/balta/classes/QueryResultRow.scala [hunk 3]
```diff
@@ -16,83 +16,154 @@
...
-  // this is not stable as resultSet mutates, but good enough for now
-  private def safe[T](fnc: => T): Option[T] = {
-    val result = fnc
-    if (resultSet.wasNull()) {
-      None
-    } else {
-      Some(result)
-    }
-  }
+class QueryResultRow private[classes](val rowNumber: Int,
```
Comment (lsulak) [inline balta/src/main/scala/za/co/absa/db/balta/classes/QueryResultRow.scala:33]: `rowNumber` is never used. Is some functionality yet to be added?

File: balta/src/test/resources/db/postgres/06_testing.pg_types.ddl [hunk 4]
```diff
@@ -0,0 +1,11 @@
...
+(
+    id bigint NOT NULL,
+    json_type json,
+    jsonb_type jsonb,
+    array_of_json_type json[],
+    PRIMARY KEY (id)
+);
+
+ALTER TABLE IF EXISTS testing.pg_types
+    OWNER to mag_owner;
```
Comment (lsulak) [inline balta/src/test/resources/db/postgres/06_testing.pg_types.ddl:11]: GH says that most of these SQL files have no newline at the end of the file

File: balta/src/test/resources/db/postgres/01_db.ddl [hunk 5]
```diff
@@ -0,0 +1,6 @@
+CREATE DATABASE mag_db
```
Comment (lsulak) [inline balta/src/test/resources/db/postgres/01_db.ddl:1]: why `mag_` ? :D

File: balta/src/test/resources/db/postgres/05_testing._base_types_data.sql [hunk 6]
```diff
@@ -0,0 +1,13 @@
+DELETE FROM testing.base_types;
```
Comment (lsulak) [inline balta/src/test/resources/db/postgres/05_testing._base_types_data.sql:1]: truncate better? also in the other query in 07 file

File: .github/workflows/test_filenames_check.yml [hunk 7]
```diff
@@ -0,0 +1,41 @@
+#
+# Copyright 2021 ABSA Group Limited
```
Comment (lsulak) [inline .github/workflows/test_filenames_check.yml:2]:
```suggestion
# Copyright 2023 ABSA Group Limited
```

File: balta/src/test/scala/za/co/absa/db/balta/implicits/PostgresRowIntegrationTests.scala [hunk 8]
```diff
@@ -0,0 +1,78 @@
...
+
+import org.scalatest.funsuite.AnyFunSuiteLike
+import za.co.absa.db.balta.classes.{DBTable, QueryResultRow}
+import za.co.absa.db.balta.testing.classes.DBTestingConnection
+
+import java.sql.ResultSetMetaData
+import Postgres.PostgresRow
+import za.co.absa.db.balta.classes.simple.SimpleJsonString
+
+class PostgresRowIntegrationTests extends AnyFunSuiteLike  with DBTestingConnection{
```
Comment (lsulak) [inline balta/src/test/scala/za/co/absa/db/balta/implicits/PostgresRowIntegrationTests.scala:27]:
```suggestion
class PostgresRowIntegrationTests extends AnyFunSuiteLike with DBTestingConnection{
```

File: balta/src/test/scala/za/co/absa/db/balta/implicits/PostgresRowIntegrationTests.scala [hunk 9]
```diff
@@ -0,0 +1,78 @@
...
+  private val (tableRows: List[QueryResultRow], metadata: ResultSetMetaData) = DBTable("testing.pg_types").all("id") { q =>
+    (q.toList, q.resultSetMetaData)
+  }
+
+  test("fieldNamesFromMetada") {
+    val result = QueryResultRow.fieldNamesFromMetdata(metadata)
+
+    val expecedResult = Seq(
```
Comment (lsulak) [inline balta/src/test/scala/za/co/absa/db/balta/implicits/PostgresRowIntegrationTests.scala:35]:
```suggestion
    val expectedResult = Seq(
```

File: balta/src/test/scala/za/co/absa/db/balta/implicits/PostgresRowIntegrationTests.scala [hunk 10]
```diff
@@ -0,0 +1,78 @@
...
+      "id",
+      "json_type",
+      "jsonb_type",
+      "array_of_json_type"
+    )
+      .zipWithIndex
+      .map(x => (x._1, x._2 + 1))
+      .toMap
+    assert(result.size == 4)
+    assert(result == expecedResult)
```
Comment (lsulak) [inline balta/src/test/scala/za/co/absa/db/balta/implicits/PostgresRowIntegrationTests.scala:45]:
```suggestion
    assert(result == expectedResult)
```

File: balta/src/test/scala/za/co/absa/db/balta/implicits/PostgresRowIntegrationTests.scala [hunk 11]
```diff
@@ -0,0 +1,78 @@
...
+  }
+
+  test("getArrayJson") {
+    //first row
+    val expected = Vector(
+      SimpleJsonString("""{"a": 2, "body": "Hold the line!"}"""),
+      SimpleJsonString("""{"a": 3, "body": ""}"""),
+      SimpleJsonString("""{"a": 4}""")
+    )
+    assert(tableRows.head.getSJSArray(4).get == (expected))
```
Comment (lsulak) [inline balta/src/test/scala/za/co/absa/db/balta/implicits/PostgresRowIntegrationTests.scala:71]:
```suggestion
    assert(tableRows.head.getSJSArray(4).get == expected)
```

?

File: balta/src/test/scala/za/co/absa/db/balta/classes/QueryResultRowIntegrationTests.scala [hunk 12]
```diff
@@ -0,0 +1,221 @@
...
+      "int_type",
+      "double_type",
+      "float_type",
+      "bigdecimal_type",
+      "date_type",
+      "time_type",
+      "timestamp_type",
+      "timestamptz_type",
+      "uuid_type",
+      "array_int_type")
```
Comment (lsulak) [inline balta/src/test/scala/za/co/absa/db/balta/classes/QueryResultRowIntegrationTests.scala:49]: this formatting is killing me :D

File: balta/src/main/scala/za/co/absa/db/balta/classes/QueryResult.scala (hunk 2 above)
Comment (benedeki) [reply balta/src/main/scala/za/co/absa/db/balta/classes/QueryResult.scala:44]: Forgotten TODO. I was actually re-throwing the exception for debugging purposes. Removed the re-throw, forgot the TODO note.
Will remove.

File: balta/src/main/scala/za/co/absa/db/balta/classes/QueryResultRow.scala (hunk 3 above)
Comment (benedeki) [reply balta/src/main/scala/za/co/absa/db/balta/classes/QueryResultRow.scala:33]: _IntelliJ_ is to eager on this reporting IMHO.
This is a library. Right here in the library, the property is not used. But in tests it actually can be used.

File: balta/src/test/resources/db/postgres/06_testing.pg_types.ddl (hunk 4 above)
Comment (benedeki) [reply balta/src/test/resources/db/postgres/06_testing.pg_types.ddl:11]: Will double check.

**Review by lsulak — COMMENTED** [review]
I finished the review for now, I like it - especially the tests you implemented and integrated them into CI!

File: balta/src/test/scala/za/co/absa/db/balta/classes/QueryResultRowIntegrationTests.scala (hunk 12 above)
Comment (benedeki) [reply balta/src/test/scala/za/co/absa/db/balta/classes/QueryResultRowIntegrationTests.scala:49]: What exactly? :-S

File: balta/src/main/scala/za/co/absa/db/balta/classes/QueryResultRow.scala (hunk 3 above)
Comment (lsulak) [reply balta/src/main/scala/za/co/absa/db/balta/classes/QueryResultRow.scala:33]: hmm, the reasoning of having a parameter supplied by caller to callee and having such parameter never used is just odd - caller knows about this parameter / value already anyway since he must supply it

I don't understand the reasoning about tests & I don't think that it makes sense to have something for tests only for benefit of tests 🤔

File: balta/src/main/scala/za/co/absa/db/balta/classes/QueryResult.scala (hunk 2 above)
Comment (lsulak) [reply balta/src/main/scala/za/co/absa/db/balta/classes/QueryResult.scala:44]: sure, I kind of thought so, it makes sense 👍

File: balta/src/test/scala/za/co/absa/db/balta/classes/QueryResultRowIntegrationTests.scala (hunk 12 above)
Comment (lsulak) [reply balta/src/test/scala/za/co/absa/db/balta/classes/QueryResultRowIntegrationTests.scala:49]:
```scala
    val expecedResult = Seq(
      "long_type",
      "boolean_type",
      "char_type",
      "string_type",
      "int_type",
      "double_type",
      "float_type",
      "bigdecimal_type",
      "date_type",
      "time_type",
      "timestamp_type",
      "timestamptz_type",
      "uuid_type",
      "array_int_type"
   )
```

i.e. parenthesis aligned with each other

File: balta/src/test/resources/db/postgres/01_db.ddl (hunk 5 above)
Comment (benedeki) [reply balta/src/test/resources/db/postgres/01_db.ddl:1]: Well you had to notice, didn't you. 😉 
Well, I sense there are parts that might become common to _balta_, _fa-db_, _ultet_ (🤭 ) justifying a shared basic lib (mag = seed in Hu)

File: balta/src/test/scala/za/co/absa/db/balta/classes/QueryResultRowIntegrationTests.scala (hunk 12 above)
Comment (lsulak) [reply balta/src/test/scala/za/co/absa/db/balta/classes/QueryResultRowIntegrationTests.scala:49]: but I don't want to deal with these things as this is already an overcame problem with correctly set auto formatters, which you hate :(

File: balta/src/test/resources/db/postgres/01_db.ddl (hunk 5 above)
Comment (lsulak) [reply balta/src/test/resources/db/postgres/01_db.ddl:1]: curiosity is my superpower :D

Comment (lsulak) [reply balta/src/test/resources/db/postgres/01_db.ddl:1]: Okay, makes sense!

File: balta/src/main/scala/za/co/absa/db/balta/classes/QueryResultRow.scala (hunk 3 above)
Comment (benedeki) [reply balta/src/main/scala/za/co/absa/db/balta/classes/QueryResultRow.scala:33]: Well the `rowNumber` is provided by `QueryResult` when it creates the `QueryResultRow`, it's not available to the user of the iterator (user of _Balta_ library) directly, but only via the `QueryResultRow` the iterator `QueryResult` returns.

File: balta/src/test/scala/za/co/absa/db/balta/classes/QueryResultRowIntegrationTests.scala [hunk 13]
```diff
@@ -0,0 +1,221 @@
...
+    val expected = UUID.fromString("090416f8-7da0-4598-844b-63659334e5b6")
+    assert(tableRows.head.getUUID(13).contains(expected))
+    assert(tableRows.head.getUUID("uuid_type").contains(expected))
+    //second row
+    val secondRow = tableRows.tail.head
+    assert(secondRow.getUUID(13).isEmpty)
+    assert(secondRow.getUUID("uuid_type").isEmpty)
+  }
+
+  test("getVector[Int]") {
```
Comment (miroslavpojer) [inline balta/src/test/scala/za/co/absa/db/balta/classes/QueryResultRowIntegrationTests.scala:210]: We are testing a `getArray` method using a `Vector`. The name should be related to the tested method, not the used solution.

**Review by miroslavpojer — COMMENTED** [review]
- [x] pull
- [ ] code review

I am missing:
- code coverage measuring.

Nice work.

File: balta/src/main/scala/za/co/absa/db/balta/classes/QueryResultRow.scala (hunk 3 above)
Comment (lsulak) [reply balta/src/main/scala/za/co/absa/db/balta/classes/QueryResultRow.scala:33]: Hmm, that sounds okay

**Review by lsulak — DISMISSED** [review]
Gonna approve from my side now, looks good! However Miroslav had a good point or two, please check his comments before merging

**Comment by benedeki** [comment]
> 
> I am missing:
> 
>     * code coverage measuring.
> 
This is more a hobby project than an official stream of work, so I don't even dare to target for some coverage. RIght now the test coverage is rather low. So either the limit would be rather low, or the check failing constantly. I don't see the point. 🤷‍♂️

**Review by miroslavpojer — APPROVED** [review]
- [x] pull
- [x] code review
- [ ] IT test run
